# Welcome {.unnumbered}

This is the website for "Human Geography through Merseyside - Quantitative Block: Seeing Liverpool through numbers" (module **ENVS162**) at the University of Liverpool. This block of the module is designed and delivered by Dr. Zi Ye and Dr. Ron Mahabir from the Geographic Data Science Lab at the University of Liverpool. The module seeks to provide hands-on experience and training in introductory statistics for human geographers.

The website is **free to use** and is licensed under the [Attribution-NonCommercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/). A compilation of this web course is hosted as a GitHub repository that you can access:

-   As an [html website](https://gdsl-ul.github.io/quant).
-   As a [GitHub repository](https://github.com/GDSL-UL/quant).

## Contact {.unnumbered}

> Zi Ye - zi.ye \[at\] liverpool.ac.uk Lecturer in Geographic Information Science Office 107, Roxby Building, University of Liverpool - 74 Bedford St S, Liverpool, L69 7ZT, United Kingdom.

> Ron Mahabir - Ron.Mahabir \[at\] liverpool.ac.uk Lecturer in Geographic Data Science Office 4xx, Roxby Building, University of Liverpool - 74 Bedford St S, Liverpool, L69 7ZT, United Kingdom.

