% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrreprt}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{luacolor}
  \usepackage[soul]{lua-ul}
\else
  \usepackage{soul}
  
\fi
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Human Geography through Merseyside - Quantitative Block: Seeing the world through numbers},
  pdfauthor={Zi Ye and Ron Mahabir},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Human Geography through Merseyside - Quantitative Block: Seeing
the world through numbers}
\author{Zi Ye and Ron Mahabir}
\date{2026-01-29}

\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\bookmarksetup{startatroot}

\chapter*{Welcome}\label{welcome}
\addcontentsline{toc}{chapter}{Welcome}

\markboth{Welcome}{Welcome}

This is the website for ``Human Geography through Merseyside -
Quantitative Block: Seeing the world through numbers'' (module
\textbf{ENVS162}) at the University of Liverpool. This block of the
module is designed and delivered by Dr.~Zi Ye and Dr.~Ron Mahabir from
the Geographic Data Science Lab at the University of Liverpool. The
module seeks to provide hands-on experience and training in introductory
statistics for human geographers.

The website is \textbf{free to use} and is licensed under the
\href{https://creativecommons.org/licenses/by-nc-nd/4.0/}{Attribution-NonCommercial-NoDerivatives
4.0 International}. A compilation of this web course is hosted as a
GitHub repository that you can access:

\begin{itemize}
\tightlist
\item
  As an \href{https://gdsl-ul.github.io/quant}{html website}.
\item
  As a \href{https://github.com/GDSL-UL/quant}{GitHub repository}.
\end{itemize}

\section*{Contact}\label{contact}
\addcontentsline{toc}{section}{Contact}

\markright{Contact}

\begin{quote}
Zi Ye - zi.ye {[}at{]} liverpool.ac.uk Lecturer in Geographic
Information Science Office 107, Roxby Building, University of Liverpool
- 74 Bedford St S, Liverpool, L69 7ZT, United Kingdom.
\end{quote}

\begin{quote}
Ron Mahabir - Ron.Mahabir {[}at{]} liverpool.ac.uk Lecturer in
Geographic Data Science Office 4xx, Roxby Building, University of
Liverpool - 74 Bedford St S, Liverpool, L69 7ZT, United Kingdom.
\end{quote}

\bookmarksetup{startatroot}

\chapter*{Overview}\label{overview}
\addcontentsline{toc}{chapter}{Overview}

\markboth{Overview}{Overview}

\section*{Aim and Learning
Objectives}\label{aim-and-learning-objectives}
\addcontentsline{toc}{section}{Aim and Learning Objectives}

\markright{Aim and Learning Objectives}

This sub-module aims to provide training and skills on a set of basic
quantitative skills for data collection, analysis, and interpretation
and to enable you to link conceptual ideas with real world examples.
\textbf{This block serves as the foundation for Year 2 BA field class
and, optionally, for Year 3 dissertation.}

\textbf{Background}

Data and research are key pillars of the global economy and society
today. We need rigorous approaches to collecting and analysing both the
statistics that can tell us `how much' and if there are observable
relationships between phenomena; and the information gives us a nuanced
understanding of cultural contexts and human dynamics. Quantitative
skills enable us to explore and measure socio-economic activities and
processes at large scales, while qualitative skills enable understanding
of social, cultural, and political contexts and diverse lived
experiences. Rather than being in opposition, qualitative and
quantitative research can complement one another in the investigation of
today's pressing research questions.

To these ends, this block will help you develop your quantitative
skills, as critical tools. This course will help you understand what
quantitative statistical researchers use and develop a set of research
techniques that can be used in your field classes and dissertations.

\textbf{Learning objectives:}

\begin{itemize}
\tightlist
\item
  Understand how to explore a dataset, containing a number of
  observations described by a set of variables.
\item
  Demonstrate an understanding in the application and interpretation of
  commonly used quantitative research methods.
\item
  Ability to work with quantitative data to understand real-world social
  phenomenian and patterns.
\end{itemize}

\section*{Module Structure}\label{module-structure}
\addcontentsline{toc}{section}{Module Structure}

\markright{Module Structure}

\textbf{Staff:} Dr Zi Ye and Dr Ron Mahabir

\textbf{Where and When}

\textbf{Week 1 - 5 Lecture:} \textbf{Tuesday} \textbf{(12am -- 1pm)}
\textbf{@} Mathematical Sciences, Proudman Lecture Theatre

\textbf{Week 1 - 6 Practical PC session: Friday (9 -- 11 am)} \textbf{@}
Central Teaching Lab: PC Teaching Centre

Lectures will introduce and explain the fundamentals of quantitative
methods, with the opportunity to apply the method introduced in the labs
later in the week.

The computer practical sessions, will give you the chance to use and
apply quantitative methods to real-world data. These are primarily
self-directed sessions, but with support on hand if you get stuck.
Support and training in R will be provided through these sessions.
Weekly sessions will be driven by empirical research questions.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0598}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.5385}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3162}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.0684}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Week
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Topic
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Format
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Staff
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & Introduction

Getting Started in RStudio: Knowing Merseyside & Lecture

Computer Lab Practical & ZY/RM \\
2 & Exploratory Data Analysis: UK Election & Lecture and Computer Lab
Practical & ZY \\
3 & Sampling and data manipulation: Happiness around the world & Lecture
and Computer Lab Practical & ZY \\
4 & Correlation, data reliability and the issue of scale: Health &
Lecture and Computer Lab Practical & RM \\
5 & How robust are my findings & Lecture and Computer Lab Practical &
RM \\
6 & Online Assessment & Computer Lab & RM/ZY \\
\end{longtable}

\section*{Software and Data}\label{software-and-data}
\addcontentsline{toc}{section}{Software and Data}

\markright{Software and Data}

For quantitative training sessions, ensure you have installed and/or
have access to \textbf{RStudio}. To run the analysis and reproduce the
code in R, you need the following software installed on your machine:

\begin{itemize}
\tightlist
\item
  R-4.2.2 (or later)
\item
  RStudio 2022.12.0-353 (or later)
\end{itemize}

To install and update:

\begin{itemize}
\tightlist
\item
  R, download the appropriate version from
  \href{https://cran.r-project.org/}{The Comprehensive R Archive Network
  (CRAN)}.
\item
  RStudio, download the appropriate version from
  \href{https://posit.co/download/rstudio-desktop/}{here}.
\end{itemize}

\textbf{This software is already installed on University Machines. But
you will need it to run the analysis on your personal devices.}

\textbf{Data}

Example datasets could be accessed through Canvas or (some) on
\href{https://github.com/GDSL-UL/stats}{GitHub} Repository of the
module. These include:

\begin{itemize}
\tightlist
\item
  2021 UK Census Data.
\item
  2021 Annulation Population Survey (APS) - only on Canvas.
\item
  2016 Family Resource Survey (FRS) - only on Canvas.
\item
  2011 Sample of Anonymised Records (SAR).
\end{itemize}

\emph{Note: The Annual Population Survey requires the completion of a
quiz prior to its usage, as it is licensed.}

\bookmarksetup{startatroot}

\chapter*{Assessment}\label{assessment}
\addcontentsline{toc}{chapter}{Assessment}

\markboth{Assessment}{Assessment}

\textbf{Week 6 Computer-based `open book' multiple-choice exam}

\begin{itemize}
\item
  The online assessment will be released at \textbf{4pm on Thursday 5th
  March} and should be c\textbf{ompleted by 4pm on Friday 6th March.}
\item
  \textbf{Also available 06/03/2025 9:00 -- 11:00 CTL PC Teaching Centre
  (1st Floor CTL)}
\item
  Should take less \textbf{90 minute}s; c.~20 questions; 24 hours to
  complete
\item
  Questions and answers randomised for each student (anti-cheating
  measure)
\item
  Some questions of factual recall, more requiring data analysis to find
  answers
\end{itemize}

\textbf{\emph{Preparation for assessment}}

\begin{itemize}
\item
  Weekly lecture \& weekly computer practical `clinic sessions'
\item
  Weekly holding hands formative tasks at the last 20 mins of the
  practical session
\item
  Week 5 mock online test
\end{itemize}

\bookmarksetup{startatroot}

\chapter{Lab: Getting Started in
RStudio}\label{lab-getting-started-in-rstudio}

\section{\texorpdfstring{\textbf{Overview}}{Overview}}\label{overview-1}

This practical intend to prepare students who have limited experiences
with R and RStudio. The content are adapted based on

\begin{itemize}
\item
  Brunsdon, Chris, and Lex Comber. 2018. \emph{An Introduction to r for
  Spatial Analysis and Mapping (2e)}. Sage.
\item
  Comber, Lex, and Chris Brunsdon. 2021. \emph{Geographical Data Science
  and Spatial Data Analysis: An Introduction in r}. Sage.
\end{itemize}

\section{\texorpdfstring{\textbf{Getting set up with
RStudio}}{Getting set up with RStudio}}\label{getting-set-up-with-rstudio}

\subsection{\texorpdfstring{\textbf{Install R and RStudio (if
necessary)}}{Install R and RStudio (if necessary)}}\label{install-r-and-rstudio-if-necessary}

R is a free, open-source programming language used for statistical
analysis, data visualization, and data science

RStudio is a free front-end to R, designed to make using R easier

All of the PCs in the University PC Teaching Centre used for this class
come with R and RStudio pre-installed, as do the PCs in many other
University PC Teaching Centres.

However, you may wish to install R and RStudio on your own computer, or
on a University PC that lacks them.

\textbf{University computers}: Use the \emph{Install University
Applications} app on the computer to install the latest version of
RStudio (this will also install the latest version of R)

\textbf{Your own computer}: R and RStudio can be downloaded from the
CRAN website and installed your own computer - see below for details.
\ul{\textbf{A key point is that you should install R before you install
RStudio.}}

The simplest way to get R installed on your computer is to go the
download pages on the R website - a quick search for `download R' should
take you there, but if not you could try:

\begin{itemize}
\item
  Windows: \url{https://cran.r-project.org/bin/windows/base/}
\item
  Mac: \url{https://cran.r-project.org/bin/macosx/}
\item
  Linux: \url{http://cran.r-project.org/bin/linux/}
\end{itemize}

The Windows and Mac version come with installer packages and are easy to
install whilst the Linux binaries require use of a command terminal.

RStudio can be downloaded from
\url{https://www.rstudio.com/products/rstudio/download/} and the free
version of RStudio Desktop is more than sufficient for this module and
all the other things you will to do at degree level.

If you experience any problems installing R or RStudio on your own
computer, bring it to one of the class lab sessions where we will be
able to provide advice.

\subsection{File management}\label{file-management}

Before you start installing software or downloading data, create a
folder on your M-Drive (if working on a University networked machine) or
locally if working on your own device -- name this `ENVS162' and within
this create a sub-folder for each practical session. For this session,
create a sub-folder called~\texttt{Week1}~in your~\texttt{ENVS162}
folder on your M-Drive. Take care to ensure you do not delete any work
you do complete in the practical sessions. It is imperative that you
practice good file management!

\subsection{\texorpdfstring{\textbf{Open
RStudio}}{Open RStudio}}\label{open-rstudio}

RStudio provides an interface to the different things that R can do via
the 4 panes: the Console where code is entered (bottom left), a Source
pane with R scripts (top left), the variables in the working Environment
(top right), Files, Plots, Help etc (bottom right) - see the RStudio
environment in Figure below.

In the figure above of the RStudio interface, a new script has been
opened, a line of code had been written and then run in the console. The
code assigns a value of 100 to \texttt{x}. The file has been saved into
the current working environment. You are expected to define a similar
set up for each practical as you work through the code. Note that
\textbf{in the script}, anything that follows a \texttt{\#} is a comment
and ignored by R.

Users can set up their personal preferences for how they like their
RStudio interface. Similar to straight R, there are very few pull-down
menus in R, and therefore you will type lines of code into your script
and run these in what is termed a \emph{command line interface} (the
console). Like all command line interfaces, the learning curve is steep
but the interaction with the software is more detailed which allows
greater flexibility and precision in the specification of commands.

Beyond this there are further choices to be made. Commands can be
entered in two forms: directly into the \emph{R console} window or as a
series of commands into a script window. We strongly advise that all
code should be \textbf{written in a script} - (a \texttt{.R} file) and
then \textbf{run from the script}. - To run code in a script, place the
cursor on the line of code and then run by pressing the `Run' icon at
the top left of the script pane, or by pressing \textbf{Ctrl Enter} (PC)
(or \textbf{Cmd Enter} on a Mac).

\pandocbounded{\includegraphics[keepaspectratio]{labs/images/clipboard-1359090391.png}}

\subsection{Ways of working}\label{ways-of-working}

The first set of consideration relate to \emph{how} you should work in
R/RStudio. The key things to remember are:

\begin{itemize}
\item
  R is a learning curve if you have never done anything like this
  before. It can be scary. It can be intimidating. But once you have a
  bit of familiarity with how things work, it is incredibly powerful.
\item
  You will be working from practical worksheets which will have all the
  code you need. Your job is to try to \textbf{understand} what the code
  is doing and \textbf{not} to remember the code. Comments in your code
  really help.
\item
  To help you do this, the very strong suggestion is use the R scripts
  that are provided, and that you add your own comments to help you
  understand what is going on when you return to them. Comments are
  prefaced by a hash (\texttt{\#}) that is ignored by R. Then you can
  save your code (with comments), run it and return to it later and
  modify at your leisure.
\end{itemize}

The module places a strong emphasis placed on learning by doing, which
means that you encouraged to unpick the code that you are given, adapt
it and play with it. It is not about remembering or being able to recall
each function used but about understanding what is being done. If you
can remember what you did previously (i.e.~the operations you undertook)
and understand what you did, you will be able to return to your code the
next time you want to do something similar. To help you with this you
should:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Always run your code from an R script\ldots{} \textbf{always}! These
  are provided for each practical;
\item
  Annotate you scripts with comments. These are prefixed by a hash
  (\texttt{\#}) in the code;
\item
  Save your R script to your folder.
\end{enumerate}

\begin{itemize}
\item
  You should always use a script (a text file containing code) for your
  code which can be saved and then re-run at a later date.
\item
  You can write your own code into a script, copy and paste code into it
  or use an existing script (for example as provided for each of the
  R/RStudio practicals in this module).
\item
  To open a new R script go to File \textgreater{} New File
  \textgreater{} R Script to open a new R file, and save it with a
  sensible name.
\item
  To load an existing script file go to File \textgreater{} Open File
  and then navigate to your file. Or, if you have recently opened the
  file, go to File \textgreater{} Recent Files \textgreater.
\item
  It is good practice to set the working directory at the beginning of
  your R session. This can be done via the menu in RStudio Session
  \textgreater{} Set Working Directory \textgreater{} \ldots. This
  points the R session to the folder you choose and will ensure that any
  files you wish to read, write or save are placed in this directory.
\item
  To run code in a script, place the cursor on the line of code and then
  run by pressing the `Run' icon at the top left of the script pane, or
  by pressing Ctrl Enter (PC) or Cmd Enter (Mac).
\end{itemize}

\subsection{Your first R code}\label{your-first-r-code}

In this section you will undertake a few generic operations. You will:

\begin{itemize}
\item
  undertake \textbf{assignment}: the allocation of values to an R
  object.
\item
  use assignment to create a \textbf{vector} of elements and a
  \textbf{matrix} of elements.
\item
  undertake \textbf{operations} on R objects.
\item
  apply some \textbf{functions} to R objects (functions nearly always
  return a value).
\item
  access some of R in-built data to examine a data table (or
  \texttt{data.frame} which is like an Excel spreadsheet).
\item
  do some basic \textbf{plotting}, including scatter plots and
  histograms.
\item
  create data summaries.
\end{itemize}

On the way you will also be introduced to \textbf{indexing}.

First, you should \textbf{create a new R script} (see above) and save it
as \texttt{week1.R} in the working directory you are using for this
practical. This should be the \texttt{Week1} sub-directory you created
in the \texttt{ENVS162} folder. Note that you should create a separate
folder for each week's practical.

\subsubsection{Assignment}\label{assignment}

The command line prompt in the Console window, the
\texttt{\textgreater{}}, is an invitation to start typing in your
commands.

Write the following into your script: \texttt{3+5} and run it. Recall
that code is run done by either by pressing the Run icon at the top left
of the script pane, or by pressing \textbf{Ctrl Enter} (PC) or
\textbf{Cmd Enter} (Mac).

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{3}\SpecialCharTok{+}\DecValTok{5}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 8
\end{verbatim}

Here the result is 8. The \texttt{{[}1{]}} that precedes the output it
formally indicates, \emph{first requested element will follow}. In this
case there is just one element. The \texttt{\textgreater{}} indicates
that R is ready for another command.

Now type the following in to your script and run it:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y }\OtherTok{\textless{}{-}} \DecValTok{3}\SpecialCharTok{+}\DecValTok{5}
\NormalTok{y}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 8
\end{verbatim}

Here the value of the \texttt{3+5} has been \textbf{\emph{assigned}} to
\texttt{y}. The syntax \texttt{y\ \textless{}-\ 3+5} can be read as
\texttt{y} \textbf{\emph{gets}} \texttt{3+5}. When \texttt{y} is invoked
its value is returned (8).

For the purposes of this module, in R the equals sign (\texttt{=}) is
the same as \texttt{\textless{}-}, a left diamond bracket
\texttt{\textless{}} followed by a minus sign \texttt{-}. This too is
interpreted by R as \textbf{\emph{is assigned to}} or
\textbf{\emph{gets}} when the code is read \textbf{right to left}.

Now copy and paste the following into your R script and run both lines:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{8}\NormalTok{), }\AttributeTok{nrow =} \DecValTok{4}\NormalTok{)}
\NormalTok{y }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{8}\NormalTok{, }\AttributeTok{nrow =} \DecValTok{4}\NormalTok{, }\AttributeTok{byrow =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

You should see the \texttt{x} appear with the \texttt{y} in the
Environment pane. \texttt{y} has now been overwritten with a new
assignment. If you click on the icon next to them, you will get a
`spreadsheet' view of the data you have created.

Of course you can also enter the following in the console and see what
is returned:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{y}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
\end{verbatim}

\textbf{Note} In the code snippets above you have used
\texttt{parentheses} - round brackets. Different kinds of brackets are
used in different ways in R. Parentheses are used with
\textbf{functions}, and contain the \textbf{arguments} that are passed
to the function, separated by commas (\texttt{,}).

In this case the functions are \texttt{c()} and \texttt{matrix()}. The
function \texttt{c()} combines or concatenates elements into a vector,
and \texttt{matrix()} creates a matrix of elements in a tabular format.

In the line of code
\texttt{x\ =\ matrix(c(1,2,3,4,5,6,7,8),\ nrow\ =\ 4)}, the arguments
passed to the \texttt{matrix()} function are the vector of values
\texttt{c(1,2,3,4,5,6,7,8)} and \texttt{nrow\ =\ 4}. Other kinds of
brackets are used in different ways as you will see later.

One final thing to note is that the matrix is \texttt{y} is has the
numbers 1 to 8, but this is specified by \texttt{1:8}. Try entering
\texttt{3:65}, \texttt{19:11}, and \texttt{1.5:5} to see how the colon
(\texttt{:}) works in this context.

\subsubsection{Operations}\label{operations}

Now you can undertake \emph{operations} on R objects and apply
\emph{functions} to them. Write the following code into your script and
then run it:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# x is a matrix}
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# multiplication}
\NormalTok{x}\SpecialCharTok{*}\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
     [,1] [,2]
[1,]    2   10
[2,]    4   12
[3,]    6   14
[4,]    8   16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sum of x}
\FunctionTok{sum}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# mean of x}
\FunctionTok{mean}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 4.5
\end{verbatim}

Operations can be undertaken directly using mathematical notation like
\texttt{*} for multiplication or using functions like \texttt{max} to
find the maximum value in an R object.

\subsubsection{Functions}\label{functions}

Functions are always followed by parenthesis (round brackets)
\texttt{(\ )}. These are different from square and curly brackets
\texttt{{[}\ {]}} and \texttt{\{\ \}}. Functions always return
something, a result if you like, and have the generic form:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# don\textquotesingle{}t run this or write this into your script!}
\NormalTok{result }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(value or R object, other parameters)}
\end{Highlighting}
\end{Shaded}

Do not run or enter this code in your script - it is an example!

\subsubsection{Data Tables}\label{data-tables}

Here we will load a data table in \texttt{data.frame} (like a
spreadsheet) in R/RStudio. R has number of in-built datasets that we can
use the code below loads one of these:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(mtcars)}
\FunctionTok{class}\NormalTok{(mtcars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "data.frame"
\end{verbatim}

Have a look at what is loaded by listing the objects in the current R
session

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ls}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "mtcars" "x"      "y"     
\end{verbatim}

You should see the \texttt{mtcars} object. You can examine this data in
a number of ways

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# the structure of mtcars}
\FunctionTok{str}\NormalTok{(mtcars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# the first six rows (or head) of mtcars}
\FunctionTok{head}\NormalTok{(mtcars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
\end{verbatim}

The \texttt{mtcars} object is a \texttt{data.frame}, a kind of data
table, and it has a number of attributes which are all numeric. The code
below prints it all out to the console:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
\end{verbatim}

Data frames are `flat' in that they typically have a rectangular layout
like a spreadsheet, with rows typically relating to observations
(individuals, areas, people, houses, etc) and columns relating to their
properties or attributes (height, age, etc). The columns in data frames
can be of different types: vectors of numbers, factors (classes) or text
strings. In matrices all of the columns have to be off the same type.
Data frames are central to what we will do in R.

\subsubsection{Plotting the data: `Hello
World!'}\label{plotting-the-data-hello-world}

The code below creates a plot of 2 variables counts in the data:
\texttt{mpg} and \texttt{disp}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(disp }\SpecialCharTok{\textasciitilde{}}\NormalTok{ mpg,  }\AttributeTok{data =}\NormalTok{ mtcars, }\AttributeTok{pch=}\DecValTok{16}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-12-1.pdf}}

The option \texttt{pch=16} sets the plotting character to a solid black
dot. More plot characters are available - examine the help for
\texttt{points()} to see these (For any command, if you are the first
time use it, you can always ask R to explain to you by using ? as help)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{?points}
\end{Highlighting}
\end{Shaded}

This plot can be improved greatly. We can specify more informative axis
labels, change size of the text and of the plotting symbol, and so on.

We can also specify the same plot by passing named variables to the
\texttt{plot} function directly as well as other parameters, as in the
figure. Notice how the syntax for this is different to the \texttt{plot}
function above, and the different \textbf{parameters} that are passed to
the \texttt{plot()} function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =}\NormalTok{ mtcars}\SpecialCharTok{$}\NormalTok{mpg, }\AttributeTok{y =}\NormalTok{ mtcars}\SpecialCharTok{$}\NormalTok{disp,   }\AttributeTok{pch =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{"dodgerblue"}\NormalTok{, }
     \AttributeTok{cex =} \FloatTok{1.5}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"Miles per Gallon"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Displacement"}\NormalTok{, }
     \AttributeTok{main =} \StringTok{"Hello World!"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-14-1.pdf}}

Notice how the dollar sign (\texttt{\$}) is used to access variables in
the \texttt{mtcars} data table compared to the first plot command, which
specified \texttt{data\ =\ mtcars}.

\subsubsection{Data summaries and
indexing}\label{data-summaries-and-indexing}

We may for example require information on variables in \texttt{mtcars}.
The \texttt{summary} function is very useful:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(mtcars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000  
 Median :0.0000   Median :4.000   Median :2.000  
 Mean   :0.4062   Mean   :3.688   Mean   :2.812  
 3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :1.0000   Max.   :5.000   Max.   :8.000  
\end{verbatim}

This shows different summaries of the individual attributes in
\texttt{mtcars}.

The main R graphics function is \texttt{plot()}. In addition to
\texttt{plot()} there are functions for adding points and lines to
existing graphs, for placing text at specified positions, for specifying
tick marks and tick labels, for labelling axes, and so on.

There are various other alternative helpful forms of graphical summary.
A helpful graphical summary for the \texttt{mtcars} data frame is the
scatterplot matrix.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# return the names of the mtcars variables}
\FunctionTok{names}\NormalTok{(mtcars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# return the 3rd to 7th names}
\FunctionTok{names}\NormalTok{(mtcars)[}\FunctionTok{c}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{7}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "disp" "hp"   "drat" "wt"   "qsec"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# check what this does}
\FunctionTok{c}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 3 4 5 6 7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# plot the 3rd to 7th variables in mtcars}
\FunctionTok{plot}\NormalTok{(mtcars[, }\FunctionTok{c}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{7}\NormalTok{)], }\AttributeTok{cex =} \FloatTok{0.5}\NormalTok{, }
     \AttributeTok{col =} \StringTok{"red"}\NormalTok{, }\AttributeTok{upper.panel=}\NormalTok{panel.smooth)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-19-1.pdf}}

The results show the correlations between the variables in the
\texttt{mtcars} data frame, and the trend of their relationship is
included with the \texttt{upper.panel=panel.smooth} parameter passed to
\texttt{plot}.

There are number of things to notice here (as well as the figure). In
particular note the use of the vector \texttt{c(2:7)} to subset the
columns of \texttt{mtcars}:

\begin{itemize}
\item
  In the second line, this is was used to subset the vector of column
  names created by \texttt{names(mtcars)}.
\item
  In the third line, it was printed out. Notice how \texttt{3:7} printed
  out all the number between 3 and 7 - very useful.
\item
  For the plot, the vector was passed to the second argument, after the
  comma, in the square brackets \texttt{{[},{]}} to indicate which
  columns were to be plotted.
\end{itemize}

The referencing in this way (or \emph{indexing}) is \textbf{very
important}: the individual rows and columns of 2 dimensional data
structures like data frames, matrices, tibbles etc can be accessed by
passing references to them in the square brackets.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1st row}
\NormalTok{mtcars[}\DecValTok{1}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
          mpg cyl disp  hp drat   wt  qsec vs am gear carb
Mazda RX4  21   6  160 110  3.9 2.62 16.46  0  1    4    4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3rd column}
\NormalTok{mtcars[,}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] 160.0 160.0 108.0 258.0 360.0 225.0 360.0 146.7 140.8 167.6 167.6 275.8
[13] 275.8 275.8 472.0 460.0 440.0  78.7  75.7  71.1 120.1 318.0 304.0 350.0
[25] 400.0  79.0 120.3  95.1 351.0 145.0 301.0 121.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# a selection of rows}
\NormalTok{mtcars[}\FunctionTok{c}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,}\DecValTok{8}\NormalTok{),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
\end{verbatim}

Such indexing could of course have been assigned to a R object and used
to do the subsetting:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{7}\NormalTok{)}
\FunctionTok{names}\NormalTok{(mtcars)[x]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "disp" "hp"   "drat" "wt"   "qsec"
\end{verbatim}

Thus indexing allows specific rows and columns to be extracted from the
data as required.

\textbf{Note} You have encountered a second type of brackets, square
brackets \texttt{{[}\ {]}}. These are used to reference or
\textbf{index} positions in a vector or a data table.

Consider the object \texttt{x} above. It contains a vector of values,
\texttt{3,4,5,6,7}. Entering \texttt{x{[}1{]}} would extract the first
element of \texttt{x}, in this case 3. Similarly \texttt{x{[}4{]}} would
return the 4th element and \texttt{x{[}c(1,4){]}} would return the 1st
and 4th elements of \texttt{x}.

However, in the examples above that index the 2-dimensional
\texttt{mtcars} object, the square brackets are used to index
\textbf{row} and \textbf{column} positions. The syntax for this is
\texttt{{[}rows,\ columns{]}}. We will be using such indexing throughout
this module.

You can ask R to return you specific rows and columns by different ways:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars[}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{9}\NormalTok{), }\DecValTok{3}\SpecialCharTok{:}\DecValTok{7}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
               disp  hp drat    wt  qsec
Mazda RX4 Wag 160.0 110 3.90 2.875 17.02
Merc 230      140.8  95 3.92 3.150 22.90
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars[}\DecValTok{3}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\StringTok{"disp"}\NormalTok{,}\StringTok{"hp"}\NormalTok{,}\StringTok{"qsec"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                  disp  hp  qsec
Datsun 710         108  93 18.61
Hornet 4 Drive     258 110 19.44
Hornet Sportabout  360 175 17.02
Valiant            225 105 20.22
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mtcars [, }\FunctionTok{c}\NormalTok{(}\StringTok{"wt"}\NormalTok{,}\StringTok{"gear"}\NormalTok{,}\StringTok{"cyl"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
                       wt gear cyl
Mazda RX4           2.620    4   6
Mazda RX4 Wag       2.875    4   6
Datsun 710          2.320    4   4
Hornet 4 Drive      3.215    3   6
Hornet Sportabout   3.440    3   8
Valiant             3.460    3   6
Duster 360          3.570    3   8
Merc 240D           3.190    4   4
Merc 230            3.150    4   4
Merc 280            3.440    4   6
Merc 280C           3.440    4   6
Merc 450SE          4.070    3   8
Merc 450SL          3.730    3   8
Merc 450SLC         3.780    3   8
Cadillac Fleetwood  5.250    3   8
Lincoln Continental 5.424    3   8
Chrysler Imperial   5.345    3   8
Fiat 128            2.200    4   4
Honda Civic         1.615    4   4
Toyota Corolla      1.835    4   4
Toyota Corona       2.465    3   4
Dodge Challenger    3.520    3   8
AMC Javelin         3.435    3   8
Camaro Z28          3.840    3   8
Pontiac Firebird    3.845    3   8
Fiat X1-9           1.935    4   4
Porsche 914-2       2.140    5   4
Lotus Europa        1.513    5   4
Ford Pantera L      3.170    5   8
Ferrari Dino        2.770    5   6
Maserati Bora       3.570    5   8
Volvo 142E          2.780    4   4
\end{verbatim}

\subsubsection{Packages}\label{packages}

The \texttt{base} installation of R includes many functions and
commands. However, more often we are interested in using some particular
functionality, encoded into \textbf{packages} contributed by the R
developer community. Installing packages for the first time can be done
at the command line in the R console using the \texttt{install.packages}
command as in the example below to install the \texttt{tmap} library or
via the RStudio menu via \textbf{Tools \textgreater{} Install Packages}.

When you install these packages it is strongly suggested you also
install the \emph{dependencies}. These are other packages that are
required by the package that is being installed. This can be done by
selecting check the box in the menu or including \texttt{dep=TRUE} in
the command line as below (don't run this yet!):

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# don\textquotesingle{}t run this!}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{, }\AttributeTok{dep =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

You may have to set a \textbf{mirror} site from which the packages will
be downloaded to your computer. Generally you should pick one that is
nearby to you.

Further descriptions of packages, their installation and their data
structures will be given as needed in the practicals. There are
literally 1000s of packages that have been contributed to the R project
by various researchers and organisations. These can be located by name
at
\url{http://cran.r-project.org/web/packages/available_packages_by_name.html}
if you know the package you wish to use. It is also possible to search
the CRAN website to find packages to perform particular tasks at
\url{http://www.r-project.org/search.html}. Additionally many packages
include user guides and vignettes as well as a PDF document describing
the package and listed at the top of the index page of the help files
for the package.

As well as \texttt{tidyverse} you should install the \texttt{sf} package
and dependencies. So we have 2 packages to install:

\begin{itemize}
\item
  \texttt{sf} for spatial data and spatial objects
\item
  \texttt{tidyverse} for lots of lovely data science things - see
  \href{https://www.tidyverse.org/}{https://www.tidyverse.org}
\end{itemize}

You could do this in one go and this will take a bit of time:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"sf"}\NormalTok{, }\StringTok{"tidyverse"}\NormalTok{), }\AttributeTok{dep =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Remember: you will only have to install a package once!! So when the
above code has run in your script you should comment it out. For example
you might want to include something like the below in your R script.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# packages only need to be loaded once}
\CommentTok{\# install.packages(c("sf", "tidyverse"), dep = TRUE)}
\end{Highlighting}
\end{Shaded}

Once the package has been installed on your computer then the package
can be called using the \texttt{library()} function into each of your R
sessions as below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(sf)}
\end{Highlighting}
\end{Shaded}

\section{Knowing Merseyside}\label{knowing-merseyside}

\subsection{Merseyside districts}\label{merseyside-districts}

Now we use these basic R command and newly installed packages to start
our initial exploration by using some existing secondary dataset from
the Census 2021.

In R we normally read in tabular dataset from .csv format. In your
\href{https://canvas.liverpool.ac.uk/courses/85565}{ENVS162 Canvas page}
find Week 1 -\textgreater{} Practical 1 Dataset, download the four
datasets to your current working folder on your M drive (ENVS162 - Week
1). You may first identify one \texttt{.csv} dataset:
\textbf{merseyside.csv}. You can open them in excel to have a look, but
here we are using R instead of Excel to load and examine them.

\subsubsection{Loading tabular data}\label{loading-tabular-data}

The survey data can be loaded into RStudio using the \texttt{read.csv}
function.

However, you will need to tell R where to get the data from. The easiest
way to do this is to use the menu if the R script file is open. Go to
\textbf{Session \textgreater{} Set Working Directory \textgreater{} To
Source File Location} to set the working directory to the location where
your \texttt{week1.R} script is saved. When you do this you will see
line of code print out in the Console (bottom left pane) similar to
\texttt{setwd("SomeFilePath")}. You can copy this line of code to your
script and paste into the line above the line calling the
\texttt{read.csv} function.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# use read.csv to load a CSV file}
\CommentTok{\# this is assignment to an object called \textasciigrave{}df\textasciigrave{}}
\NormalTok{df }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\AttributeTok{file =} \StringTok{"merseyside.csv"}\NormalTok{, }\AttributeTok{stringsAsFactors =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The \texttt{stringsAsFactors\ =\ TRUE} parameter tells R to read any
character or text variables as classes or categories and not as just
text.

You could inspect the help for the \texttt{read.csv} function to see the
different parameters and their default values:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{help}\NormalTok{(read.csv)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
starting httpd help server ... done
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# or }
\NormalTok{?read.csv}
\end{Highlighting}
\end{Shaded}

Functions always return something and in this case \texttt{read.csv()}
function has returned a tabular R object with 5 records and 12 fields.
This has been \emph{assigned to} \texttt{df}.

Finally in this section, lets have a look at the data. This can be done
in a number of ways.

\begin{itemize}
\item
  you could look at the \texttt{df} object by entering \texttt{df} in
  the Console. However this is not particular helpful as it simply
  prints out everything that is in \texttt{df} to the Console.
\item
  you could click on the \texttt{df} object in the Environment pane and
  this shows the structure of the attributes in different fields.
\item
  you could click on the little grid-like icon next \texttt{df} in the
  Environment pane to get a \texttt{View} of the data and remember to
  close the tab that opens!.
\item
  or you could use some code as in the examples below.
\end{itemize}

First, let's have a look at the internal structure of the data using the
\texttt{str} function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   5 obs. of  12 variables:
 $ LAD21CD           : Factor w/ 5 levels "E08000011","E08000012",..: 1 2 3 4 5
 $ District          : Factor w/ 5 levels "Knowsley","Liverpool",..: 1 2 4 3 5
 $ Population        : int  154519 486089 183248 279234 320196
 $ Households        : int  66073 207491 81011 123075 143253
 $ Working_population: int  69495 205749 82622 124596 139500
 $ Students          : int  7050 59628 7582 12636 14642
 $ Unemployed        : int  3852 13894 4076 6143 6542
 $ Age_over_65       : int  26242 74322 37642 64763 70391
 $ Disability        : int  34990 105962 40829 61134 73088
 $ No_central_heating: int  1020 4822 1003 1965 2125
 $ Overcrowding      : int  1892 7352 1888 2700 2355
 $ Working_from_home : int  14880 53721 18973 34750 37299
\end{verbatim}

There is other ways to get info about the number of rows and columns:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ncol}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#or both row and col}
\FunctionTok{dim}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1]  5 12
\end{verbatim}

The~\texttt{head}~function does this by printing out the first six
records of the data table and you may need to scroll up and down in the
Console pane to see all of what is returned.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    LAD21CD   District Population Households Working_population Students
1 E08000011   Knowsley     154519      66073              69495     7050
2 E08000012  Liverpool     486089     207491             205749    59628
3 E08000013 St. Helens     183248      81011              82622     7582
4 E08000014     Sefton     279234     123075             124596    12636
5 E08000015     Wirral     320196     143253             139500    14642
  Unemployed Age_over_65 Disability No_central_heating Overcrowding
1       3852       26242      34990               1020         1892
2      13894       74322     105962               4822         7352
3       4076       37642      40829               1003         1888
4       6143       64763      61134               1965         2700
5       6542       70391      73088               2125         2355
  Working_from_home
1             14880
2             53721
3             18973
4             34750
5             37299
\end{verbatim}

Another way to explore the data is through
the~\texttt{summary}~function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
      LAD21CD        District   Population       Households    
 E08000011:1   Knowsley  :1   Min.   :154519   Min.   : 66073  
 E08000012:1   Liverpool :1   1st Qu.:183248   1st Qu.: 81011  
 E08000013:1   Sefton    :1   Median :279234   Median :123075  
 E08000014:1   St. Helens:1   Mean   :284657   Mean   :124181  
 E08000015:1   Wirral    :1   3rd Qu.:320196   3rd Qu.:143253  
                              Max.   :486089   Max.   :207491  
 Working_population    Students       Unemployed     Age_over_65   
 Min.   : 69495     Min.   : 7050   Min.   : 3852   Min.   :26242  
 1st Qu.: 82622     1st Qu.: 7582   1st Qu.: 4076   1st Qu.:37642  
 Median :124596     Median :12636   Median : 6143   Median :64763  
 Mean   :124392     Mean   :20308   Mean   : 6901   Mean   :54672  
 3rd Qu.:139500     3rd Qu.:14642   3rd Qu.: 6542   3rd Qu.:70391  
 Max.   :205749     Max.   :59628   Max.   :13894   Max.   :74322  
   Disability     No_central_heating  Overcrowding  Working_from_home
 Min.   : 34990   Min.   :1003       Min.   :1888   Min.   :14880    
 1st Qu.: 40829   1st Qu.:1020       1st Qu.:1892   1st Qu.:18973    
 Median : 61134   Median :1965       Median :2355   Median :34750    
 Mean   : 63201   Mean   :2187       Mean   :3237   Mean   :31925    
 3rd Qu.: 73088   3rd Qu.:2125       3rd Qu.:2700   3rd Qu.:37299    
 Max.   :105962   Max.   :4822       Max.   :7352   Max.   :53721    
\end{verbatim}

Finally in this section, we come back to the dollar sign (\texttt{\$}).
This is used to refer to or \emph{extract} an individual named field or
variable in an R object, like \texttt{df}.

The code below prints out the Population attribute and generates a
summary of its values:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# extract an individual variable}
\NormalTok{df}\SpecialCharTok{$}\NormalTok{Population}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 154519 486089 183248 279234 320196
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# generate a summary of an individual variable}
\FunctionTok{summary}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Population)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 154519  183248  279234  284657  320196  486089 
\end{verbatim}

And of course we can use such operations to~\emph{assign}~the result to
new R objects. The code below extracts three variables from~\texttt{df},
assigns them to~\texttt{x},~\texttt{y}~and~\texttt{z}, and then uses
the~\texttt{data.frame}~function to convert these into a
new~\texttt{data.frame}~object called~\texttt{my\_df}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# extract three variables, assigning them to temporary R objects}
\NormalTok{x }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{District}
\NormalTok{y }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Working\_population}
\NormalTok{z }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Students}
\CommentTok{\# create a data.frame from these, naming the new variables}
\NormalTok{my\_df }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{district =}\NormalTok{ x,}\AttributeTok{worker =}\NormalTok{ y,}\AttributeTok{student =}\NormalTok{ z)}
\end{Highlighting}
\end{Shaded}

You should have a look at what you have created:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(my\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    district worker student
1   Knowsley  69495    7050
2  Liverpool 205749   59628
3 St. Helens  82622    7582
4     Sefton 124596   12636
5     Wirral 139500   14642
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(my\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
       district     worker          student     
 Knowsley  :1   Min.   : 69495   Min.   : 7050  
 Liverpool :1   1st Qu.: 82622   1st Qu.: 7582  
 Sefton    :1   Median :124596   Median :12636  
 St. Helens:1   Mean   :124392   Mean   :20308  
 Wirral    :1   3rd Qu.:139500   3rd Qu.:14642  
                Max.   :205749   Max.   :59628  
\end{verbatim}

The temporary R objects can be removed from the Environment using
the~\texttt{rm}~function and a~\emph{combine}~vector
function,~\texttt{c()}~that you encountered in Week 19, that takes a
vector of object names (hence they are in quotes) as its arguments.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list =} \FunctionTok{c}\NormalTok{(}\StringTok{"x"}\NormalTok{,}\StringTok{"y"}\NormalTok{,}\StringTok{"z"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\subsubsection{Basic data manipulation}\label{basic-data-manipulation}

Now we can do some basic data manipulation to know Merseyside more from
the data perspective.

What is the total population in Merseyside?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Population)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1423286
\end{verbatim}

What is the total number of full-time students in Merseyside?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Students)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 101538
\end{verbatim}

Then, we can calculate the total number of workers that working from
home:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Working\_from\_home)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 159623
\end{verbatim}

What is the proportion of working population actually work from home in
Merseyside? Yes, we need to use a division calculation of the total
number of working from home vs.~all the working population. R can do it
by:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Working\_from\_home) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Working\_population)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 0.2566443
\end{verbatim}

So the answer is 25.7\% for the whole Merseyside - but which district
has the highest proportion and which as the lowest? You may have your
own guessing. But let R do the calculation:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df}\SpecialCharTok{$}\NormalTok{Prop.WFH }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Working\_from\_home }\SpecialCharTok{/}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Working\_population }\CommentTok{\#add a new column called Prop.WFH}
\NormalTok{df }\CommentTok{\#print out the df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
    LAD21CD   District Population Households Working_population Students
1 E08000011   Knowsley     154519      66073              69495     7050
2 E08000012  Liverpool     486089     207491             205749    59628
3 E08000013 St. Helens     183248      81011              82622     7582
4 E08000014     Sefton     279234     123075             124596    12636
5 E08000015     Wirral     320196     143253             139500    14642
  Unemployed Age_over_65 Disability No_central_heating Overcrowding
1       3852       26242      34990               1020         1892
2      13894       74322     105962               4822         7352
3       4076       37642      40829               1003         1888
4       6143       64763      61134               1965         2700
5       6542       70391      73088               2125         2355
  Working_from_home  Prop.WFH
1             14880 0.2141161
2             53721 0.2610997
3             18973 0.2296362
4             34750 0.2789014
5             37299 0.2673763
\end{verbatim}

Here we ask R to add a new column named \texttt{Prop.WFH} which is the
working from home proportion that calculated by the number of working
from home people in each district divided by the total working
population in that district. R will automatically do it row-by-row. We
then print out the \texttt{df}, you may find at the very right end of
the tabular, there is a new column called \texttt{Prop.WFH}.

For a very small dataframe like this, we can also using View() to open a
new tab to review the data, where each column can be sorted from largest
to smallest or vice versa. Try viewing it and find the newly created
column \texttt{Prop.WFH}. Click on the column name, you should see it is
sorted from highest to lowest, and click again, the ranking is reversed.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Your first map for
Merseyside}\label{your-first-map-for-merseyside}

Now let's try to do our first map in R and allow yourself know more
about Merseyside.

We will use the library sf and tmap to help us at here. Run the install
codes if you haven't install them. Remember: you will only have to
install a package once!!

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"tmap"}\NormalTok{,}\AttributeTok{dep =}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Check the package version of tmap, as here we need to use tmap over 4.0
version.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{packageVersion}\NormalTok{(}\StringTok{"tmap"}\NormalTok{) }\CommentTok{\# the version should over 4.0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] '4.1'
\end{verbatim}

When they have been installed, we can start using them

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(sf)}
\FunctionTok{library}\NormalTok{(tmap)}
\end{Highlighting}
\end{Shaded}

You may find in Week 1 data, we have another file named
\emph{merseyside\_districts.gpkg}. A GeoPackage (GPKG) is a file-based
format designed for storing geographic data. It supports the efficient
storage and exchange of spatial datasets and can be readily used across
GIS software such as QGIS and ArcGIS, as well as in programming
environments including R and Python.

We first read it in by using the \texttt{st\_read()} command in library
sf.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sf }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(}\StringTok{"merseyside\_districts.gpkg"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Reading layer `lad_may_2025_uk_bgc_v2_4306843991635065087__lad_may_2025_uk_bgc_v2' from data source `C:\Users\ziye\Documents\GitHub\quant\labs\merseyside_districts.gpkg' 
  using driver `GPKG'
Simple feature collection with 5 features and 8 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 318351.7 ymin: 377515.4 xmax: 361796.3 ymax: 422866.5
Projected CRS: OSGB36 / British National Grid
\end{verbatim}

The fastest way to map it is the \texttt{qtm()} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qtm}\NormalTok{(sf)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-49-1.pdf}}

You can also add the district names on the map - which column in the sf
contains district name? Use \texttt{names(sf)} to check for it.

Yes, the column should be \texttt{LAD25NM}. Now let's ask \texttt{qtm()}
to also show the district names.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qtm}\NormalTok{(sf,}\AttributeTok{text=}\StringTok{"LAD25NM"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-50-1.pdf}}

But what if we want to make some meaningful maps, rather than just the
boundaries of these five districts of Merseyside?

\subsubsection{Link tabular data to geographical
boundaries}\label{link-tabular-data-to-geographical-boundaries}

Recall that in our \texttt{df}, we have 14 columns, containing different
information about the districts. We can get all their names by using
\texttt{names()}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "LAD21CD"            "District"           "Population"        
 [4] "Households"         "Working_population" "Students"          
 [7] "Unemployed"         "Age_over_65"        "Disability"        
[10] "No_central_heating" "Overcrowding"       "Working_from_home" 
[13] "Prop.WFH"          
\end{verbatim}

We can do the same thing for our geographical dataset \texttt{sf} to see
what it includes:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "LAD25CD"  "LAD25NM"  "LAD25NMW" "BNG_E"    "BNG_N"    "LONG"     "LAT"     
[8] "GlobalID" "geom"    
\end{verbatim}

We can also show the whole \texttt{sf} as

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sf}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Simple feature collection with 5 features and 8 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 318351.7 ymin: 377515.4 xmax: 361796.3 ymax: 422866.5
Projected CRS: OSGB36 / British National Grid
    LAD25CD    LAD25NM LAD25NMW  BNG_E  BNG_N      LONG      LAT
1 E08000011   Knowsley          344762 393778 -2.832979 53.43789
2 E08000012  Liverpool          339359 390556 -2.913680 53.40833
3 E08000013 St. Helens          353413 395992 -2.703093 53.45862
4 E08000014     Sefton          334282 398835 -2.991771 53.48213
5 E08000015     Wirral          329109 386965 -3.067034 53.37478
                                GlobalID                           geom
1 {B4196BFE-EE90-4C31-ABD5-C7E743AE2F9B} MULTIPOLYGON (((341447.1 40...
2 {4FB47E7A-EF4E-4B9E-BF75-D4FC059CDE61} MULTIPOLYGON (((338860.9 39...
3 {943F0C6B-EB30-4C00-A42B-F6B3AEC3EFEE} MULTIPOLYGON (((349111.4 40...
4 {C6FD073B-CBEB-4E78-934A-A8FD11A20F0A} MULTIPOLYGON (((336374.5 42...
5 {88E9328B-371C-469C-91F1-3479C77D6950} MULTIPOLYGON (((331364.9 39...
\end{verbatim}

Now we see that sf includes also the five districts, but also other
geographical information. You may notice that although different column
names, the first two columns of both df and sf are the district code and
district name. This means what potentially we can link this two dataset
together - appendix the df to sf to enrich the attributes of our
geographical dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{merseyside }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(sf, df,}\AttributeTok{by=}\FunctionTok{c}\NormalTok{(}\StringTok{"LAD25NM"}\OtherTok{=}\StringTok{"District"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

let's check out the new \texttt{sf2} by \texttt{View()} it:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(merseyside)}
\end{Highlighting}
\end{Shaded}

In the open tab, we see all the \texttt{df} columns are now also
attached to the \texttt{sf}, linking by the district names.

\subsubsection{Choropleth map of Merseyside
districts}\label{choropleth-map-of-merseyside-districts}

Now, we can use those new columns we attached from \texttt{df} to
\texttt{sf2} to make some meaningful choropleth maps! Here we make use
of the mapping functions in tmap (Remember to run \texttt{library(tmap)}
if you haven't) to do the work for us.

\texttt{tmap} has a basic syntax (again, do not run this code - its is
simply showing the syntax of \texttt{tmap}):

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# don\textquotesingle{}t run this or write this into your script!}
\FunctionTok{tm\_shape}\NormalTok{(}\AttributeTok{data =} \SpecialCharTok{\textless{}}\NormalTok{data}\SpecialCharTok{\textgreater{}}\NormalTok{)}\SpecialCharTok{+}
\NormalTok{  tm\_}\SpecialCharTok{\textless{}}\ControlFlowTok{function}\SpecialCharTok{\textgreater{}}\NormalTok{(}\SpecialCharTok{\textless{}}\NormalTok{variable to be mapped}\SpecialCharTok{\textgreater{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

For example, to map the boundaries of \texttt{merseyside}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+} 
  \FunctionTok{tm\_borders}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-57-1.pdf}}

To add label of district:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+} 
  \FunctionTok{tm\_borders}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{tm\_text}\NormalTok{(}\StringTok{"LAD25NM"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-58-1.pdf}}

You might assume the quick mapping function \texttt{qtm()} can achieve
the same result, but \texttt{tmap} provides far more flexibility when it
comes to aesthetic customization. The easiest way to illustrate
\texttt{tmap} is through some examples.

Let's start with a simple choropleth map, by using \texttt{tmap} to show
the distribution of a continuous variable in different elements of the
spatial data (here are the data Merseyside districts are polygons).

The code below maps `\texttt{Students}' as in the Merseyside districts,
and shows the district names of each polygon from `\texttt{LAD25NM}'
columns. The map below indicates that Liverpool has the highest number
of full-time students while Knowsley and St.Helens have the least.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+} 
  \FunctionTok{tm\_polygons}\NormalTok{(}\AttributeTok{fill =} \StringTok{"Students"}\NormalTok{) }\SpecialCharTok{+}   \CommentTok{\# Variable to map }
  \FunctionTok{tm\_text}\NormalTok{(}\StringTok{"LAD25NM"}\NormalTok{)                 }\CommentTok{\# Variable to label}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-59-1.pdf}}

By default tmap picks a shading scheme, the class breaks and places a
legend somewhere. All of these can be changed. The code below allocates
the tmap plot to \texttt{map1} (Map 1), change the legend title as
``Number of students in Merseyside districts'', and then prints it:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map1  }\OtherTok{=} \FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+} 
  \FunctionTok{tm\_polygons}\NormalTok{(}\AttributeTok{fill=}\StringTok{"Students"}\NormalTok{,}
              \AttributeTok{fill.scale =} \FunctionTok{tm\_scale}\NormalTok{(}\AttributeTok{values =} \StringTok{"Greens"}\NormalTok{), }\CommentTok{\# change palette to greens}
              \AttributeTok{fill.legend =} \FunctionTok{tm\_legend}\NormalTok{(}\AttributeTok{title =} \StringTok{"Number of students in Merseyside districts"}\NormalTok{)}
\NormalTok{              ) }\SpecialCharTok{+}\CommentTok{\# Legend title}
  \FunctionTok{tm\_text}\NormalTok{(}\StringTok{"LAD25NM"}\NormalTok{)}
\NormalTok{map1}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-60-1.pdf}}

And of course many other elements included either by running the code
snippet defining \texttt{map1} above with additional lines or by simply
adding them as in the code below:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map1 }\SpecialCharTok{+} 
  \FunctionTok{tm\_scalebar}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{)) }\SpecialCharTok{+} 
  \FunctionTok{tm\_compass}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"left"}\NormalTok{, }\StringTok{"top"}\NormalTok{))  }\CommentTok{\# Use "top", "center", or "bottom"}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-61-1.pdf}}

We can also create new variable to the dataset and then map it. The
below code chunk first creates a new column,
``\texttt{NoCentralHeating\_rate}'', by dividing the number of
households without access to central heating by the total number of
households in each district; it then uses \texttt{tmap} to make a map of
the proportion of households without central heating across districts in
Merseyside:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{merseyside}\SpecialCharTok{$}\NormalTok{NoCentralHeating\_rate }\OtherTok{=}\NormalTok{ merseyside}\SpecialCharTok{$}\NormalTok{No\_central\_heating }\SpecialCharTok{/}\NormalTok{ merseyside}\SpecialCharTok{$}\NormalTok{Households }\SpecialCharTok{*} \DecValTok{100}

\NormalTok{map2 }\OtherTok{=} \FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+} 
  \FunctionTok{tm\_polygons}\NormalTok{(}\AttributeTok{fill=}\StringTok{"NoCentralHeating\_rate"}\NormalTok{,}
              \AttributeTok{fill.scale =} \FunctionTok{tm\_scale}\NormalTok{(}\AttributeTok{values =} \StringTok{"Reds"}\NormalTok{, }\AttributeTok{style =} \StringTok{"jenks"}\NormalTok{), }\CommentTok{\#use jenks classification rather than equal}
              \AttributeTok{fill.legend =} \FunctionTok{tm\_legend}\NormalTok{(}\AttributeTok{title =} \StringTok{"\% No Central Heating"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{tm\_text}\NormalTok{(}\StringTok{"LAD25NM"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_scalebar}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{)) }\SpecialCharTok{+}  \CommentTok{\# Add a scale bar at the top{-}right corner}
  \FunctionTok{tm\_compass}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"left"}\NormalTok{, }\StringTok{"top"}\NormalTok{))  }\CommentTok{\# Add a compass rose at the top{-}right corner}
\NormalTok{map2}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-62-1.pdf}}

\subsection{Merseyside neighbourhoods}\label{merseyside-neighbourhoods}

Now let's read in the neighbourhood-level datasets, which include a
\texttt{.csv} file of local statistics and the corresponding
geographical boundaries.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lsoa\_df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"merseyside\_lsoa.csv"}\NormalTok{)}
\NormalTok{lsoa\_sf }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(}\StringTok{"LSOA\_boundaries.gpkg"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Reading layer `merseyside_LSOA' from data source 
  `C:\Users\ziye\Documents\GitHub\quant\labs\LSOA_boundaries.gpkg' 
  using driver `GPKG'
Simple feature collection with 923 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -3.200368 ymin: 53.2963 xmax: -2.576743 ymax: 53.6982
Geodetic CRS:  WGS 84
\end{verbatim}

First, we take a look at the \texttt{.csv} dataset, which as been read
into R as \texttt{lsoa\_df}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(lsoa\_df)}
\end{Highlighting}
\end{Shaded}

or check the structure of the dataset:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(lsoa\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   923 obs. of  11 variables:
 $ LSOA21CD          : chr  "E01006416" "E01006418" "E01006434" "E01006435" ...
 $ Population        : int  1520 1315 1519 1524 1150 1654 1450 1581 1421 1373 ...
 $ Households        : int  678 567 652 663 490 695 592 622 809 618 ...
 $ Working_population: int  588 547 660 581 546 766 558 570 524 481 ...
 $ Students          : int  59 64 69 82 51 66 65 89 52 72 ...
 $ Unemployed        : num  3.57 2.74 5.11 3.43 1.62 ...
 $ Age_over_65       : num  14.8 17.5 11.7 19.9 26.3 ...
 $ Disability        : num  27.1 30 23.4 29 20.5 ...
 $ No_central_heating: int  16 14 16 7 3 8 9 9 12 9 ...
 $ Overcrowding      : int  24 24 35 28 13 21 29 23 31 22 ...
 $ Working_from_home : int  91 84 102 96 165 171 101 64 66 48 ...
\end{verbatim}

So now, you know how many LSOAs in Merseyside? Yes, there are 923 LSOAs.
As we introduced in the Week 1 lecture, LSOA means Super Output Area
Lower Area and is commonly used in Census statistics, representing 1,000
to 3,000 people or 400 to 1,200 households in England and Wales.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(lsoa\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 923  11
\end{verbatim}

Use the quick mapping function \texttt{qtm()} to quickly inspect the
geographical boundary dataset \texttt{lsoa\_sf} .

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qtm}\NormalTok{(lsoa\_sf)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-67-1.pdf}}

check how many LSOAs in the boundary dataset - there should also be 923.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(lsoa\_sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 923
\end{verbatim}

To familiarise yourself with the structures of both datasets, we can use
the \texttt{names()} command

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(lsoa\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "LSOA21CD"           "Population"         "Households"        
 [4] "Working_population" "Students"           "Unemployed"        
 [7] "Age_over_65"        "Disability"         "No_central_heating"
[10] "Overcrowding"       "Working_from_home" 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(lsoa\_sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "LSOA21CD" "LSOA21NM" "LAD23CD"  "LAD23NM"  "geom"    
\end{verbatim}

You may find that both dataset are recorded at the LSOA level, with
\texttt{LSOA21CD} as the key column. As we did with the district-level
dataset, we can use \texttt{left\_join()} to join these two dataset by
their sharing field - \texttt{LSOA21CD}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lsoa }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(lsoa\_sf,lsoa\_df,}\AttributeTok{by=}\StringTok{"LSOA21CD"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now let's check the columns of new dataframe \texttt{lsoa}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(lsoa)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 [1] "LSOA21CD"           "LSOA21NM"           "LAD23CD"           
 [4] "LAD23NM"            "Population"         "Households"        
 [7] "Working_population" "Students"           "Unemployed"        
[10] "Age_over_65"        "Disability"         "No_central_heating"
[13] "Overcrowding"       "Working_from_home"  "geom"              
\end{verbatim}

Or open a new tab to view the newly created dataset \texttt{lsoa} by

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(lsoa)}
\end{Highlighting}
\end{Shaded}

We can see that some columns contain counts, such as the number of
residential population, number of households, number of working
population, and number of students. Other columns are expressed as
percentages, including unemployment, population aged 65 and over,
disability, households without central heating, overcrowded households,
and people working from home.

\subsubsection{Making maps across LSOAs in
Merseyside}\label{making-maps-across-lsoas-in-merseyside}

Using the \texttt{Unemployed} column, we can create a map of the
unemployment rate across neighbourhoods in Merseyside. Instead of using
the default equal-interval breaks, this time we will use a jenks
classification with six categories.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map3 }\OtherTok{=} \FunctionTok{tm\_shape}\NormalTok{(lsoa) }\SpecialCharTok{+}
  \FunctionTok{tm\_fill}\NormalTok{(}
    \AttributeTok{fill =} \StringTok{"Unemployed"}\NormalTok{,}
    \AttributeTok{fill.scale =} \FunctionTok{tm\_scale}\NormalTok{(}\AttributeTok{values =} \StringTok{"GnBu"}\NormalTok{, }
                          \AttributeTok{style =} \StringTok{"jenks"}\NormalTok{, }
                          \AttributeTok{n =} \DecValTok{6}\NormalTok{), }\CommentTok{\#use jenks classification of 6 categories}
    \AttributeTok{fill.legend =} \FunctionTok{tm\_legend}\NormalTok{(}\AttributeTok{title =} \StringTok{"\% Unemployed"}\NormalTok{)}
\NormalTok{    ) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"top"}\NormalTok{))}
\NormalTok{map3}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-73-1.pdf}}

The above code uses
\texttt{tm\_layout(legend.position\ =\ c("right",\ "top"))} to move the
legend inside the map frame, positioning it at the right-top corner.

Replace \texttt{tm\_fill()} to \texttt{tm\_polygons()} to see how the
map changes?

\texttt{tm\_polygons()} is a condense version of
\texttt{tm\_fill()\ +\ tm\_border()}. Here if you want show all the LSOA
borders, use \texttt{tm\_polygons()} instead of \texttt{tm\_fill()}.

\subsubsection{Overlapping tmap objects}\label{overlapping-tmap-objects}

\texttt{tmap} also supports adding or overlaying other data, such as
boundaries. Because these are additional spatial data layers, they needs
to be added with \texttt{tm\_shape()} followed by the usual function.

Remember we use the code chunk to make the district boundaries of
Merseyside? This time let's change the aesthetic by using grey color as
the border color and increase the line width, then we save it also as a
\texttt{tmap} object called map\_district:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map\_district }\OtherTok{=} \FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+} 
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{col =} \StringTok{"grey50"}\NormalTok{,}\AttributeTok{lwd=}\FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\#border color as grey, line width as 1.5}
  \FunctionTok{tm\_text}\NormalTok{(}\StringTok{"LAD25NM"}\NormalTok{,}\AttributeTok{size =} \FloatTok{0.8}\NormalTok{)}
\NormalTok{map\_district}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-74-1.pdf}}

To display both \texttt{tmap} layers together, we can proceed as
follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map3 }\SpecialCharTok{+}\NormalTok{ map\_district}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-75-1.pdf}}

Now, let's move to making some more maps - this time showing the
proportion of disability across neighbourhoods in Merseyside. Referring
back to the columns in \texttt{lsoa}, this time we use the
\texttt{Disability} variable. The code below applies a jenks
classification and use a different color palette \texttt{Purples}. Also
the map frame is removed by \texttt{frame\ =\ FALSE}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\AttributeTok{fill =} \StringTok{"Disability"}\NormalTok{,}
          \AttributeTok{fill.scale =} \FunctionTok{tm\_scale}\NormalTok{(}\AttributeTok{values=}\StringTok{"Purples"}\NormalTok{, }
                                \AttributeTok{style =} \StringTok{"jenks"}\NormalTok{,}
                                \AttributeTok{n=}\DecValTok{5}\NormalTok{),}
          \AttributeTok{fill.legend =} \FunctionTok{tm\_legend}\NormalTok{(}\AttributeTok{title =} \StringTok{"\% Disability"}\NormalTok{)}
\NormalTok{          ) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"top"}\NormalTok{),}
            \AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{)}\SpecialCharTok{+}
\NormalTok{  map\_district}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-76-1.pdf}}

\subsubsection{Create new variable to make
maps}\label{create-new-variable-to-make-maps}

Similarly, we can make maps from new columns we made ourselves. For
example, we can calculate the percentage of student by adding a new
column to the dataframe:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lsoa}\SpecialCharTok{$}\NormalTok{student.perc }\OtherTok{=}\NormalTok{ lsoa}\SpecialCharTok{$}\NormalTok{Students }\SpecialCharTok{/}\NormalTok{ lsoa}\SpecialCharTok{$}\NormalTok{Population }\SpecialCharTok{*} \DecValTok{100}
\end{Highlighting}
\end{Shaded}

To make a map to visualisation the spatial distribution of student
percentage. The code below uses \texttt{n=6} to increase the
classification categories to 6 rather than default 5.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\AttributeTok{fill =} \StringTok{"student.perc"}\NormalTok{,}
          \AttributeTok{fill.scale =} \FunctionTok{tm\_scale}\NormalTok{(}\AttributeTok{values=}\StringTok{"Blues"}\NormalTok{,}
                                \AttributeTok{style =} \StringTok{"jenks"}\NormalTok{,}
                                \AttributeTok{n=}\DecValTok{6}\NormalTok{),}
          \AttributeTok{fill.legend =} \FunctionTok{tm\_legend}\NormalTok{(}\AttributeTok{title =} \StringTok{"\% of Student"}\NormalTok{,}
                                  \AttributeTok{title.size =} \FloatTok{0.8}\NormalTok{) }\CommentTok{\#legend title change smaller font}
\NormalTok{          ) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{main.title =} \StringTok{"Merseyside"}\NormalTok{,}
            \AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{,}
            \AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"top"}\NormalTok{))}\SpecialCharTok{+}
\NormalTok{  map\_district}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-78-1.pdf}}

To change the palette, R tidyverse library provide:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RColorBrewer}\SpecialCharTok{::}\FunctionTok{display.brewer.all}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.8\linewidth,height=\textheight,keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-79-1.pdf}

\subsubsection{In a nutshell}\label{in-a-nutshell}

If we want to make a map to show the rate of no central heating
households in all the neighbourhoods in Merseyside, we need to create a
new variable \texttt{no.central.heating.perc} as the result of dividing
households without central heating by total households in each LSOA. The
code below combines all the cartographic elements together:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lsoa}\SpecialCharTok{$}\NormalTok{no.central.heating.perc }\OtherTok{=}\NormalTok{ lsoa}\SpecialCharTok{$}\NormalTok{No\_central\_heating }\SpecialCharTok{/}\NormalTok{ lsoa}\SpecialCharTok{$}\NormalTok{Households}

\FunctionTok{tm\_shape}\NormalTok{(lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\AttributeTok{fill =} \StringTok{"no.central.heating.perc"}\NormalTok{,}
          \AttributeTok{fill.scale =} \FunctionTok{tm\_scale}\NormalTok{(}\AttributeTok{values=}\StringTok{"YlOrRd"}\NormalTok{,}
                                \AttributeTok{style =} \StringTok{"jenks"}\NormalTok{,}\AttributeTok{n=}\DecValTok{6}\NormalTok{),}
          \AttributeTok{fill.legend =} \FunctionTok{tm\_legend}\NormalTok{(}\AttributeTok{title =} \StringTok{"\% of no central heating households"}\NormalTok{, }
                                  \AttributeTok{title.size =} \FloatTok{0.8}\NormalTok{)}
\NormalTok{        ) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{main.title =} \StringTok{"Merseyside"}\NormalTok{,}
            \AttributeTok{main.title.size=}\FloatTok{1.2}\NormalTok{,}
            \AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{tm\_compass}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"top"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{tm\_scalebar}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{tm\_shape}\NormalTok{(merseyside) }\SpecialCharTok{+}               \CommentTok{\# Add another spatial layer (Merseyside boundary)}
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{col =} \StringTok{"black"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Draw the boundaries with black lines of width 1}
  \FunctionTok{tm\_text}\NormalTok{(}\StringTok{"LAD25NM"}\NormalTok{,}\AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}\AttributeTok{size =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{labs/01.GettingStartedinRStudio_files/figure-pdf/unnamed-chunk-80-1.pdf}}

\section{Summary}\label{summary}

The aim of this session has been to familiarise you with the R
environment if you have not used R before. If you have but not for a
while, then hopefully this has acted as a refresher. Some key things to
take away are:

\begin{itemize}
\item
  R is a learning curve, and like driving the more your practice the
  better you become.
\item
  Your job is to try to \textbf{understand} what the code is doing and
  \textbf{not} to remember the code.
\item
  To help with this, you should add your own comments to the script to
  help you understand what is going on when you return to them. Comments
  are prefaced by a hash (\texttt{\#}) that is ignored by R.
\item
  Always set your working directory to the sub-folder containing your R
  script.
\item
  Always run your code from an R script\ldots{} \textbf{always}!
\end{itemize}

\subsection{References}\label{references}

Brunsdon, Chris, and Lex Comber. 2018. \emph{An Introduction to r for
Spatial Analysis and Mapping (2e)}. Sage.

Comber, Lex, and Chris Brunsdon. 2021. \emph{Geographical Data Science
and Spatial Data Analysis: An Introduction in r}. Sage.

Harris, Richard. 2016. \emph{Quantitative Geography: The Basics}. Sage.

Other good on-line \emph{get started in R} guides include:

\begin{itemize}
\item
  The Owen guide (only up to page 28) :
  \url{https://cran.r-project.org/doc/contrib/Owen-TheRGuide.pdf}
\item
  An Introduction to R -
  \url{https://cran.r-project.org/doc/contrib/Lam-IntroductionToR_LHL.pdf}
\item
  R for beginners
  \url{https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf}
\end{itemize}

\subsection{Formative Tasks}\label{formative-tasks}

\textbf{Task 1} Use the ``merseyside\_lsoa.csv'' dataset. Plot
\texttt{Disability} against \texttt{Age\_over\_65}from the data frame.

\textbf{Task 2} Get household information of Liverool and Wirral
districts from the district level dataset ``merseyside.csv''. The
variables need to be included are ``Households'',
``No\_central\_heating'' and ``Overcrowding''.

\textbf{Task 3} Use district level dataset, how many households all
together in Merseyside?

\textbf{Task 4} Use district level dataset, what is the overall
proportion of ageing population (age over 65) in Merseyside?

\textbf{Task 5} Use the LSOA level dataset, what is the average
proportion of ageing population (age over 65) in all the neighbourhoods
of Merseyside?

\textbf{Task 6} Create a map of the spatial distribution of the
proportion of ageing population (age over 65) over LSOAs of Merseyside?
(use Jenks classification of 7 categories).




\end{document}
